name: clone_zoom
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cloud_firestore: ^5.6.11
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  flutter:
    sdk: flutter
  google_sign_in: ^7.1.0
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  jitsi_meet_flutter_sdk: ^11.3.0
  timeago: ^3.7.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding.jpg
    - assets/images/google_logo.png
    - assets/images/google_icon.png
